###
GET http://mstalk.herokuapp.com/user/users


###
POST http://mstalk.herokuapp.com/user
Content-Type: application/json

{
    "username": "Rhea",
    "first_name": "Rhea",
    "last_name": "Ardiente",
    "password": "password"
}

###
POST  http://localhost:8000/api/login
Content-Type: application/json

{
    "email":"rhea.ardiente@mlhuillier.com",
    "password": "rhea2021"
}

###
POST http://localhost:8000/api/emails
Content-Type: application/json
Authorization: Bearer HMAFbT5IbgGi2QtbLE2XtaPUY9ZrSldEfBectvZ3

{
    "user_id": 1,
    "emails": ["aparece@gmail.com1",
                "aparece@gmail.com2",
                "aparece@gmail.com3",
                "aparece@gmail.com4",
                "aparece@gmail.com5",
                "aparece@gmail.com6",
                "aparece@gmail.com7"
                ]
}

###
POST http://localhost:8000/api/forms
Content-Type: application/json

{
    "question1": "This is a test",
    "question2": "I am Beautitful",
    "question3": "Life is Challenging",
    "category1": "Good",
    "category2": "Fair",
    "category3": "Good",
    "category4": "Fair",
    "category5": "Outstanding",
    "category6": "Poor",
    "category7": "Fair",
    "category8": "Good",
    "category9": "Good",
    "category10": "Good"
}

// ok na yang
//akung
kit kiton taka run
// mag pakit
kit rah mn sd ko..
hahahhahaah ewwwwww k.a.  loud
haha
..
maslood ang mokitkit..
yuckssss...i will never do that
haha.. ma
ayu
 lisod na makitki
tan
houyyy undanga na nahh oyyyy
..........
.. kuha na nimo sa
pag integrate adto sa
angular?
dli mn akoy mo inte
grate ani c mates mn....
pwede ra sad ko nmo tudlou an
