###
GET http://mstalk.herokuapp.com/user/users


###
POST http://mstalk.herokuapp.com/user
Content-Type: application/json

{
    "username": "Rhea",
    "first_name": "Rhea",
    "last_name": "Ardiente",
    "password": "password"
}

###
POST  http://localhost:8000/api/login
Content-Type: application/json

{
    "email":"rhea.ardiente@mlhuillier.com",
    "password": "rhea2021"
}

###
POST http://localhost:8000/api/emails
Content-Type: application/json
Authorization: Bearer 1|FGMffmZWVd8Tll0uoPlCUYQQ92bxowE1oi1skDsM

{
    "user_id": 1,
    "emails": ["aparece@gmail.com1",
                "aparece@gmail.com2",
                "aparece@gmail.com3",
                "aparece@gmail.com4",
                "aparece@gmail.com5",
                "aparece@gmail.com6",
                "aparece@gmail.com7"
                ]
}


/// yang ok na
// na all ka perfect bahhh
//akung utok ga dugo
// nakuha ra nimo unsa problema ato?
//ang pag convert ..// ouh sa pag convert sa array
//ahhh okay lamats sir// welcome// geh padayun na
//cege kuya// end na nako
###
POST http://localhost:8000/api/forms
Content-Type: application/json

{
    "question1": "This is a test",
    "question2": "I am Beautitful",
    "question3": "Life is Challenging",
    "category1": "Good",
    "category2": "Fair",
    "category3": "Good",
    "category4": "Fair",
    "category5": "Outstanding",
    "category6": "Poor",
    "category7": "Fair",
    "category8": "Good",
    "category9": "Good",
    "category10": "Good"
}


// login
####

// unsa gani to link sa backend naka deploy
POST  https://mlback-end.herokuapp.com/api/login
Content-Type: application/json

{
    "email":"rhea.ardiente@mlhuillier.com",
    "password": "rhea2021"
}

// wala ni reflect ang pag return sa user dahh
/// okayyy nahhhhhh
// cge try nato to ang route na nag error..
// unsa to na route?
//huh..wala ko ka g
// nag lisod mn daw ang
//aww ga lisod daw sila ug pa display sa user nga naka log in
// ahw cge pa tri daw nila ug pa display karon..
// nag try na cla?
// nag try nahhh
//baw unsa kahay result atu....
// chat lang ko kung na ok na o wala ba..
// e end na nko
//installan kaha naku c mates ug teamviewer nohh??/
//layu d i mo? doul ra mn...para maka balo sad kas problema
// pwede rah sd..
cge end nahhhh

