###
GET http://mstalk.herokuapp.com/user/users


###
POST http://mstalk.herokuapp.com/user
Content-Type: application/json

{
    "username": "Rhea",
    "first_name": "Rhea",
    "last_name": "Ardiente",
    "password": "password"
}

###
POST  http://localhost:8000/api/login
Content-Type: application/json

{
    "email":"rhea.ardiente@mlhuillier.com",
    "password": "rhea2021"
}

###
POST http://localhost:8000/api/emails
Content-Type: application/json
Authorization: Bearer 1|FGMffmZWVd8Tll0uoPlCUYQQ92bxowE1oi1skDsM

{
    "user_id": 1,
    "emails": ["aparece@gmail.com1",
                "aparece@gmail.com2",
                "aparece@gmail.com3",
                "aparece@gmail.com4",
                "aparece@gmail.com5",
                "aparece@gmail.com6",
                "aparece@gmail.com7"
                ]
}

###

POST  https://mlback-end.herokuapp.com/api/emails
Content-Type: application/json
Authorization: Bearer 10|huBIKNfxIt5391v0KogPon9QtN2dJUSGSDTi5MfR

{
    "user_id": 1,
    "emails": ["aparece@gmail.com1",
                "aparece@gmail.com2",
                "aparece@gmail.com3",
                "aparece@gmail.com4",
                "aparece@gmail.com5",
                "aparece@gmail.com6",
                "aparece@gmail.com7"
                ]
}
###
# POST http://localhost:8000/api/forms

POST  https://mlback-end.herokuapp.com/api/emails

Content-Type: application/json
Authorization: Bearer 1|6xtJFJRlaEa3ej6qN35oV42FKy7tiRrZSUQ3V9Hn

{
    "question1": "This is a test",
    "question2": "I am Beautitful",
    "question3": "Life is Challenging",
    "category1": "Good",
    "category2": "Fair",
    "category3": "Good",
    "category4": "Fair",
    "category5": "Outstanding",
    "category6": "Poor",
    "category7": "Fair",
    "category8": "Good",
    "category9": "Good",
    "category10": "Good"
}


// login
####

POST  https://mlback-end.herokuapp.com/api/login
Content-Type: application/json

{
    "email":"reina.mates@mlhuillier.com",
    "password": "reina2021"
}

//responses
####

GET http://localhost:8000/api/responses

#####
GET https://mlback-end.herokuapp.com/api/email
Authorization: Bearer 10|huBIKNfxIt5391v0KogPon9QtN2dJUSGSDTi5MfR



###

GET http://localhost:8000/api/test
Authorization: Bearer 3|6q6A5vmPEbhNXjmTPmb8XlHYS6CVVBpfRCrx8gwt



